server:
  port: 8091
  context-path: /bill-server-8223
spring:
  application:
    name: bill-server-8223
  profiles:
    active: dev

access:
  key: xYTpAHo7DTJJgrKP
  secret: Fm6RQim9YPgH1m7VJ17euIKNyJluwu
