server:
  port: 8081
  context-path: /demand-server-8223
spring:
  application:
    name: demand-server-8223
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.20.53.69:3306/train-ddd?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource


#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.yonyou.train.core.demand.domain.entity
  mapperLocations: classpath:mapping/*Mapper.xml

access:
  key: xYTpAHo7DTJJgrKP
  secret: Fm6RQim9YPgH1m7VJ17euIKNyJluwu

