server:
  port: 8081
  context-path: /demand-server-8223
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.20.53.69:3306/train-ddd?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource


logging:
  level:
    com:
      yonyou:
        train: debug



